# Generated by Django 4.0.4 on 2022-07-24 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_rename_categorias_post_categoriass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categoriass',
            new_name='categorias',
        ),
    ]
